apiVersion: v1
kind: Service
metadata:
  name: ecozhop-service
spec:
  ports:
    - port: 8080
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: ecozhop-deployment
  type: LoadBalancer